# Generated by Django 5.0.6 on 2024-05-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usertask_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
