# Generated by Django 5.0.6 on 2024-05-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usertask_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
