# Generated by Django 5.0.6 on 2024-05-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usertask_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
