# Generated by Django 5.0.6 on 2024-05-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='TaskList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tasklist'),
        ),
    ]
