# Generated by Django 5.0.6 on 2024-05-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usertask_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='completed_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
